name: pr_check
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: install
        run: npm install pnpm -g

      - name: checkout
        uses: actions/checkout@main

      - name: test-api
        run: cd packages/api && pnpm i && pnpm run test

      - name: test-webapp
        run: cd ../webapp && pnpm i && pnpm run test

